name: release

on:
  push:
    tags:
      - v*

env:
  NODE_VERSION: "18"
  PNPM_VERSION: "7.5.0"
  GO_VERSION: "1.19.0-rc1"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
          stable: false

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Check out
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: |
            - cwd: frontend

      - name: Build wasm
        run: go build -ldflags="-s -w" -v -o frontend/static/calculator.wasm ./wasm
        env:
          GOOS: js
          GOARCH: wasm

      - name: Build frontend
        working-directory: frontend
        run: |
          pnpm run build
          ls -lah build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
          exclude_assets: ''
